/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TambahGajiGUI.java
 *
 * Created on 25 Jul 12, 15:47:41
 */
package gui;

import dao.GajiDAO;
import dao.GolonganDAO;
import dao.KaryawanDAO;
import entity.Gaji;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhurand
 */
public class TambahGajiGUI extends javax.swing.JInternalFrame {

    EntityManager em;
    boolean valid = false;

    /** Creates new form TambahGajiGUI */
    public TambahGajiGUI(EntityManager em) {
        initComponents();

        this.em = em;
        //this.HitungBonus();

        this.bindingKaryawan();

        tunjangan1_chk.setSelected(false);
        tunjangan1_txt.setEnabled(false);
        tunjangan2_chk.setSelected(false);
        tunjangan2_txt.setEnabled(false);

    }

    public void bindingKaryawan() {
        KaryawanDAO dao = new KaryawanDAO(em);
        nik_cmb.removeAllItems();
        for (int i = 0; i < dao.getAll().size(); i++) {
            nik_cmb.addItem(dao.getAll().get(i).getNIK());

        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nik_cmb = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nama_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bulan_cmb = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gajipokok_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pajak_txt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tunjangan1_chk = new javax.swing.JCheckBox();
        tunjangan2_chk = new javax.swing.JCheckBox();
        tunjangan1_txt = new javax.swing.JTextField();
        tunjangan2_txt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hari_txt = new javax.swing.JFormattedTextField();
        lembur_txt = new javax.swing.JTextField();
        cek_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        keluar_btn = new javax.swing.JButton();
        golongan_txt = new javax.swing.JTextField();

        setTitle("Tambah Gaji");

        jLabel1.setText("NIK Karyawan");

        nik_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nik_cmbActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        nama_txt.setEditable(false);

        jLabel3.setText("Bulan");

        bulan_cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        bulan_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulan_cmbActionPerformed(evt);
            }
        });

        jLabel4.setText("Golongan");

        jLabel5.setText("Gaji Pokok");

        gajipokok_txt.setEditable(false);

        jLabel6.setText("Pajak (%)");

        pajak_txt.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tunjangan"));

        tunjangan1_chk.setText("Tunjangan 1");
        tunjangan1_chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunjangan1_chkActionPerformed(evt);
            }
        });

        tunjangan2_chk.setText("Tunjangan 2");
        tunjangan2_chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunjangan2_chkActionPerformed(evt);
            }
        });

        tunjangan1_txt.setText("0");

        tunjangan2_txt.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tunjangan1_chk)
                        .addGap(18, 18, 18)
                        .addComponent(tunjangan1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tunjangan2_chk)
                        .addGap(18, 18, 18)
                        .addComponent(tunjangan2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tunjangan1_chk)
                    .addComponent(tunjangan1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tunjangan2_chk)
                    .addComponent(tunjangan2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bonus"));

        jLabel7.setText("Upah Lembur");

        jLabel8.setText("Jumlah Hari");

        hari_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        hari_txt.setText("0");
        hari_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hari_txtActionPerformed(evt);
            }
        });

        lembur_txt.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hari_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lembur_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(lembur_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hari_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        cek_btn.setText("Cek");
        cek_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cek_btnActionPerformed(evt);
            }
        });

        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });

        keluar_btn.setText("Keluar");
        keluar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar_btnActionPerformed(evt);
            }
        });

        golongan_txt.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(gajipokok_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nik_cmb, javax.swing.GroupLayout.Alignment.LEADING, 0, 122, Short.MAX_VALUE)
                                    .addComponent(pajak_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(182, 182, 182)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bulan_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(golongan_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(cek_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reset_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(keluar_btn)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nik_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(bulan_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(golongan_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gajipokok_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pajak_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset_btn)
                    .addComponent(keluar_btn)
                    .addComponent(cek_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bulan_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulan_cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulan_cmbActionPerformed

    private void hari_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hari_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hari_txtActionPerformed

    private void nik_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nik_cmbActionPerformed
        // TODO add your handling code here:

        KaryawanDAO dao = new KaryawanDAO(em);
        GolonganDAO gdao = new GolonganDAO(em);

        nama_txt.setText(dao.getByNIK(nik_cmb.getSelectedItem().toString()).get(0).getNama());
        golongan_txt.setText(dao.getByNIK(nik_cmb.getSelectedItem().toString()).get(0).getGolongan());
        gajipokok_txt.setText(String.valueOf(gdao.getByKode(golongan_txt.getText()).get(0).getGajiPokok()));
        pajak_txt.setText(String.valueOf(gdao.getByKode(golongan_txt.getText()).get(0).getPajak()));

    }//GEN-LAST:event_nik_cmbActionPerformed

    private void keluar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_keluar_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:
        bulan_cmb.setSelectedIndex(0);
        //nama_txt.setText("");
        //golongan_txt.setText("");
        //gajipokok_txt.setText("");
        //pajak_txt.setText("");

        tunjangan1_chk.setSelected(false);
        tunjangan1_txt.setText("0");
        tunjangan1_txt.setEnabled(false);

        tunjangan2_chk.setSelected(false);
        tunjangan2_txt.setText("0");
        tunjangan2_txt.setEnabled(false);

        lembur_txt.setText("0");
        hari_txt.setText("0");



        valid = false;

    }//GEN-LAST:event_reset_btnActionPerformed

    private void tunjangan1_chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunjangan1_chkActionPerformed
        // TODO add your handling code here:
        if (tunjangan1_chk.isSelected()) {
            tunjangan1_txt.setText("0");
            tunjangan1_txt.setEnabled(true);
        } else {
            tunjangan1_txt.setText("0");
            tunjangan1_txt.setEnabled(false);
        }
    }//GEN-LAST:event_tunjangan1_chkActionPerformed

    private void tunjangan2_chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunjangan2_chkActionPerformed
        // TODO add your handling code here:
        if (tunjangan2_chk.isSelected()) {
            tunjangan2_txt.setText("0");
            tunjangan2_txt.setEnabled(true);
        } else {
            tunjangan2_txt.setText("0");
            tunjangan2_txt.setEnabled(false);
        }
    }//GEN-LAST:event_tunjangan2_chkActionPerformed

    private void cek_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cek_btnActionPerformed
        // TODO add your handling code here:
        try {
            //Kode Gaji
            String kom1 = nik_cmb.getSelectedItem().toString().substring(0, 1);
            String kom2 = nama_txt.getText().substring(0, 2);
            String kom3 = golongan_txt.getText().substring(0, 2);
            String kom4 = bulan_cmb.getSelectedItem().toString().substring(0, 3);

            //Tampung data
            String kodeGaji = kom1 + kom2 + kom3 + kom4;
            
            String m1 = "Kode Gaji      :   "+kodeGaji+"\n";
            String m2 = "Bulan          :   "+bulan_cmb.getSelectedItem().toString()+"\n";
            String m3 = "Nama           :   "+nama_txt.getText()+"\n";
            String m4 = "Golongan       :   "+golongan_txt.getText()+"\n";
            String m5 = "Gaji Pokok     :   "+gajipokok_txt.getText()+"\n";
            String m6 = "Pajak (%)      :   "+pajak_txt.getText()+"\n";
            String m7 = "Tunjangan 1    :   "+tunjangan1_txt.getText()+"\n";
            String m8 = "Tunjangan 2    :   "+tunjangan2_txt.getText()+"\n";
            String m9 = "Upah Lembur    :   "+lembur_txt.getText()+"\n";
            String m10= "Jumlah Hari  :   "+hari_txt.getText()+"\n";
            
            double hitung = (Double.parseDouble(gajipokok_txt.getText())+Double.parseDouble(tunjangan1_txt.getText())+Double.parseDouble(tunjangan2_txt.getText())
                    +(Double.parseDouble(lembur_txt.getText())*Double.parseDouble(hari_txt.getText())))
                    -((Double.parseDouble(pajak_txt.getText())/100)*Double.parseDouble(gajipokok_txt.getText()));
            
            String m11 ="Gaji Bersih    :   "+String.valueOf(hitung);
            
            String message = m1+m2+m3+m4+m5+m6+m7+m8+m9+m10+m11;
            int result = JOptionPane.showConfirmDialog(this, message, "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                try {
                    GajiDAO dao = new GajiDAO(em);
                    Gaji g = new Gaji();
                    
                    g.setKode(kodeGaji);
                    g.setBulan(bulan_cmb.getSelectedItem().toString());
                    g.setNama(nama_txt.getText());
                    g.setGolongan(golongan_txt.getText());
                    g.setGajipokok(Double.parseDouble(gajipokok_txt.getText()));
                    g.setPajak(Double.parseDouble(pajak_txt.getText()));
                    g.setTunjangan1(Double.parseDouble(tunjangan1_txt.getText()));
                    g.setTunjangan2(Double.parseDouble(tunjangan2_txt.getText()));
                    g.setBonus(Double.parseDouble(lembur_txt.getText())*Double.parseDouble(hari_txt.getText()));
                    g.setGajibersih(hitung);
                    
                    JOptionPane.showMessageDialog(this, dao.Insert(g));
                    
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } else {
            }

        } catch (NumberFormatException n) {
            //n.printStackTrace();
            JOptionPane.showMessageDialog(this, "Tunjangan dan Bonus harus Di isi dengan Angka");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cek_btnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bulan_cmb;
    private javax.swing.JButton cek_btn;
    private javax.swing.JTextField gajipokok_txt;
    private javax.swing.JTextField golongan_txt;
    private javax.swing.JFormattedTextField hari_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton keluar_btn;
    private javax.swing.JTextField lembur_txt;
    private javax.swing.JTextField nama_txt;
    private javax.swing.JComboBox nik_cmb;
    private javax.swing.JTextField pajak_txt;
    private javax.swing.JButton reset_btn;
    private javax.swing.JCheckBox tunjangan1_chk;
    private javax.swing.JTextField tunjangan1_txt;
    private javax.swing.JCheckBox tunjangan2_chk;
    private javax.swing.JTextField tunjangan2_txt;
    // End of variables declaration//GEN-END:variables
}
